version: "3.7"
services:
  # pgdata:
  #   image: postgres:16.2-alpine3.19
  #   container_name: pgdata
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
  #   ports:
  #     - 8888:5432
  #   environment:
  #     - POSTGRES_USER=${POSTGRES_USER}
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #     - POSTGRES_DB=${POSTGRES_DB}

  nginx:
    image: nginx:1.25.3-alpine
    container_name: nginx
    ports:
      - 7777:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
volumes:
  # pgdata:
  #   driver: local
  nginx:
    driver: local
